### ISSUE TITLE
populate fails with Pg - TimeStamp inflator not working as expected

### ISSUE THREAD

**Issue by SysPete** [interchange/Flowers#7]
Only one change compared to stock Flowers - environments/development.yml contains:
plugins:
  DBIC:
    default:
      dsn: dbi:Pg:dbname=flowers

shop_user->create fails with:
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  null value in column "created" violates not-null constraint [for Statement "INSERT INTO users ( email, password, username) VALUES ( ?, ?, ? ) RETURNING users_id" with ParamValues: 1='racke@nite.si', 2='nevairbe', 3='racke@nite.si'] at bin/populate line 72

Flowers rev: a5a3f9b Revise checkout routes and form prefill.

I have an almost identical create in a local project which works correctly and the TS inflator inserts created/last_modified correctly. Flowers and my local project use all same Perl/DPIC6/etc versions and same PostgreSQL cluster. This is not related to PostgreSQL server since the INSERT should have had created and last_modified filled in before the insert happens. 
I'm totally baffled by this. Failure is the same whether I use my branches or upstream/master so not a bug I've introduced with Moo.

**Comment by SysPete** [comment]
This must have worked on 20th January since I submitted some patches around then. Time to play with git bisect. :-)
Checked out Flowers ca4e3f4 (populate added here) and also 40e4e44 which includes a few of my patches to populate and we get the same failure in both. Must be a change in either schema or DPIC6 - time to warp everything back to around 20th January and see what can be made to work.

**Comment by SysPete** [comment]
No dice. With schema at 5b4007a, IC6 at 6fb95b5, DPIC6 at 8ef79cf and Flowers at ca4e3f4 it still fails. I even restored my Perl tree to 20th January but that didn't help either.

**Comment by racke** [comment]
On 03/04/2014 06:05 PM, Peter Mottram wrote:

> No dice. With schema at 5b4007a, IC6 at 6fb95b5, DPIC6 at 8ef79cf and Flowers at ca4e3f4 it still fails. I even restored my Perl tree to 20th January but that didn't help either.

I switched my Flowers test shop to Pg 9.1 and it doesn't show this behaviour.

Regards
    Racke

## 

Perl and Dancer Development

Visit our Open Source conference on E-commerce:

http://www.ecommerce-innovation.com/

**Comment by SysPete** [comment]
just created a clean setup on a different system and all is well so is clearly just a problem from my side
